insert into authors (first_name, last_name) values ('Bax', 'Meigh');
insert into authors (first_name, last_name) values ('Emmalyn', 'Baitman');
insert into authors (first_name, last_name) values ('Grady', 'Cathery');
insert into authors (first_name, last_name) values ('Sampson', 'Davsley');
insert into authors (first_name, last_name) values ('Clerkclaude', 'Cardenosa');
insert into authors (first_name, last_name) values ('Fanchon', 'Schiersch');
insert into authors (first_name, last_name) values ('Whit', 'Coppeard');
insert into authors (first_name, last_name) values ('Xymenes', 'Jilkes');
insert into authors (first_name, last_name) values ('Francesco', 'Coales');
insert into authors (first_name, last_name) values ('Jolee', 'Bredes');
insert into authors (first_name, last_name) values ('Ches', 'Squire');
insert into authors (first_name, last_name) values ('Teriann', 'Lowy');
insert into authors (first_name, last_name) values ('Jinny', 'Mossom');
insert into authors (first_name, last_name) values ('Christin', 'Antrag');
insert into authors (first_name, last_name) values ('Katalin', 'Duncan');
insert into authors (first_name, last_name) values ('Glendon', 'Awcoate');
insert into authors (first_name, last_name) values ('Willard', 'Laux');
insert into authors (first_name, last_name) values ('Etta', 'Glanz');
insert into authors (first_name, last_name) values ('Minne', 'Perigeaux');
insert into authors (first_name, last_name) values ('Jesselyn', 'Gregg');
insert into authors (first_name, last_name) values ('Raviv', 'Oade');
insert into authors (first_name, last_name) values ('Dael', 'Fogt');
insert into authors (first_name, last_name) values ('Bobbie', 'Newey');
insert into books (author_id, title, price_old, price) values (1, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author_id, title, price_old, price) values (2, 'utilize real-time interfaces', '$260.31', '$260.31');
-- insert into books (author_id
--, title, price_old, price) values (2, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author_id, title, price_old, price) values (3, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author_id, title, price_old, price) values (4, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author_id, title, price_old, price) values (5, 'cultivate magnetic e-commerce', '$278.43', '$278.43');
-- insert into books (author_id
--, title, price_old, price) values (5, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author_id, title, price_old, price) values (6, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author_id, title, price_old, price) values (7, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author_id, title, price_old, price) values (8, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author_id, title, price_old, price) values (9, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author_id, title, price_old, price) values (10, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author_id, title, price_old, price) values (7, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author_id, title, price_old, price) values (12, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author_id, title, price_old, price) values (13, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author_id, title, price_old, price) values (14, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author_id, title, price_old, price) values (15, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author_id, title, price_old, price) values (16, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author_id, title, price_old, price) values (17, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author_id, title, price_old, price) values (18, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author_id, title, price_old, price) values (19, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author_id, title, price_old, price) values (7, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author_id, title, price_old, price) values (21, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author_id, title, price_old, price) values (22, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author_id, title, price_old, price) values (23, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author_id, title, price_old, price) values (11, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author_id, title, price_old, price) values (20, 'facilitate efficient eyeballs', '$232.30', '$131.48');
