package com.example.MyBookShopApp.struct.book.file;

import com.example.MyBookShopApp.data.services.ResourceStorage;
import com.example.MyBookShopApp.struct.book.book.Book;
import com.example.MyBookShopApp.struct.book.book.BookFileType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

import javax.persistence.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "book_file")
@Data
public class BookFileEntity {

//    @JsonIgnore
//    @Value(value = "${download.path}")
//    private String downloadPath;

    @ApiModelProperty(value = "this is generated by DB", position = 1)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ApiModelProperty(value = "случайный хэш, предназначенный для идентификации файла при скачивании")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String hash;

    @ApiModelProperty(value = "путь к файлу")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String path;

    @ApiModelProperty(value = "тип файла")
    @ManyToOne
    @JoinColumn(name = "type_id", referencedColumnName = "id")
    private BookFileTypeEntity bookFileTypeEntity;

//    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "book_id", referencedColumnName = "id")
    private Book book;

    @ApiModelProperty(value = "размер файла для скачивания")
    @Column(columnDefinition = "VARCHAR(50) DEFAULT ''")
    private String size;

//    public int getSize(){
//        Path path = Paths.get(downloadPath, this.path);
//        try {
//            return Files.readAllBytes(path).length;
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//        return 0;
//    }


//    public String getExtensionString(){
//        return BookFileType.getExtensionStringByTypeId(typeId);
//    }
}
