package com.example.MyBookShopApp.struct.book.file;

import com.example.MyBookShopApp.struct.book.book.Book;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.persistence.*;

@Entity
@Table(name = "book_file")
@Data
public class BookFileEntity {

    @ApiModelProperty(value = "this is generated by DB", position = 1)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @ApiModelProperty(value = "случайный хэш, предназначенный для идентификации файла при скачивании")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String hash;

    @ApiModelProperty(value = "путь к файлу")
    @Column(columnDefinition = "VARCHAR(255) NOT NULL")
    private String path;

    @ApiModelProperty(value = "размер файла для скачивания")
    @Column(columnDefinition = "VARCHAR(50) DEFAULT ''")
    private String size;

    @ApiModelProperty(value = "тип файла")
    @ManyToOne
    @JoinColumn(name = "type_id", referencedColumnName = "id")
    private BookFileTypeEntity bookFileTypeEntity;

//    @JsonIgnore
    @ManyToOne
    @JoinColumn(name = "book_id", referencedColumnName = "id")
    private Book book;

    @Override
    public String toString() {
        return "BookFileEntity{" +
                "id=" + id +
                ", hash='" + hash + '\'' +
                ", path='" + path + '\'' +
                ", bookFileTypeEntity=" + bookFileTypeEntity +
                ", size='" + size + '\'' +
                '}';
    }
}
